from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('start/', views.start, name='start'),
    path('profile/', views.profile, name='profile'),
    path('topArtists/', views.topArtists, name='topArtists'),
    path('topGenres/', views.topGenres, name='topGenres'),
    path('topSongs/', views.topSongs, name='topSongs'),
    path('totalTime/', views.totalTime, name='totalTime'),
    path('', views.home, name="home"),
    path('deleteProf/', views.deleteProf, name="deleteProf"),
    path('artistsTransition/', views.artistsTransition, name="artistsTransition"),
    path('endPage/', views.endPage, name="endPage"),
    path('genreTransition/', views.genreTransition, name="genreTransition"),
    path('introPage/', views.introPage, name="introPage"),
    path('songsTransition/', views.songsTransition, name="songsTransition"),
    path('timeTransition/', views.timeTransition, name="timeTransition"),
    path('toggleDarkMode/', views.toggleDarkMode, name="toggleDarkMode"),
    path('artistsTranDuo/', views.artistsTranDuo, name="artistsTranDuo"),
    path('endDuo/', views.endDuo, name="endDuo"),
    path('genreDuo/', views.genreDuo, name="genreDuo"),
    path('genreTranDuo/', views.genreTranDuo, name="genreTranDuo"),
    path('timeDuo/', views.timeDuo, name="timeDuo"),
    path('timeTranDuo/', views.timeTranDuo, name="timeTranDuo"),
    path('topArtistsDuo/', views.topArtistsDuo, name="topArtistsDuo"),
    path('topSongsDuo/', views.topSongsDuo, name="topSongsDuo"),
    path('topSongsTranDuo/', views.topSongsTranDuo, name="topSongsTranDuo"),
    path('welcomeDuo/', views.welcomeDuo, name="welcomeDuo"),
    path('spotifyLogin/', views.spotifyLogin, name="spotifyLogin"),
    path('userauth/', views.userauth, name="userauth"),
    path('linkSpotify/', views.linkSpotify, name="linkSpotify"),
    path('contact/', views.contact, name="contact"),
    path('savedWraps/', views.savedWraps, name="savedWraps"),
    path('gamePage/', views.gamePage, name='gamePage'),
    path('check_answer/', views.check_answer, name='check_answer'),

    path('api/search-users/', views.search_users, name='search_users'),
    path('wrapSum/', views.wrapSum, name="wrapSum"),
    path('wrapSumDuo/', views.wrapSumDuo, name="wrapSumDuo"),
    path('invite-friend/', views.invite_friend, name='invite_friend'),
    path('refreshAuth/', views.refreshAuth, name="refreshAuth"),
    path('save/', views.save, name="save"),
    path('viewWrapped/', views.viewWrapped, name="viewWrapped"),
    path('introPageOld/', views.introPageTwo, name="introPageTwo"),
    path('deleteInv/', views.deleteInv, name="deleteInv"),
    path('acceptInv/', views.acceptInv, name='acceptInv'),
    path('delete-wrap/', views.delete_wrap, name='deleteWrap'),
    path('refreshAuthDuo/', views.refreshAuthDuo, name="refreshAuthDuo"),
    path('refreshAuthDuoInv/', views.refreshAuthDuoInv, name="refreshAuthDuoInv"),
    path('welcomeDuoOld/', views.welcomeDuoTwo, name="welcomeDuoTwo"),
    path('duoSave/', views.duoSave, name="duoSave"),
    path('viewDuoWrapped/', views.viewDuoWrapped, name="viewDuoWrapped"),
    path('deletWrapDuo/', views.deleteWrapDuo, name="deleteWrapDuo"),
    path('wrapSum/', views.wrap_sum, name='wrap_sum'),
    path('endPageTwo/', views.endPageTwo, name='endPageTwo'),
    path('endDuoTwo/', views.endDuoTwo, name='endDuoTwo'),
    path('redirectPage/', views.redirectPage, name='redirectPage'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)